// <auto-generated />
using System;
using Metaspesa.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Metaspesa.Database.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20260504180106_AddUrls")]
    partial class AddUrls
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Metaspesa.Database.Entities.ProductBrandDbEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_product_brand");

                    b.HasIndex(new[] { "Name" }, "idx_product_brand_name")
                        .IsUnique();

                    b.ToTable("product_brands", "market", t =>
                        {
                            t.HasComment("Brands of products available in the market");
                        });
                });

            modelBuilder.Entity("Metaspesa.Database.Entities.ProductDbEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("integer")
                        .HasColumnName("brand_id");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SuperMarketId")
                        .HasColumnType("integer")
                        .HasColumnName("super_market_id");

                    b.HasKey("Id")
                        .HasName("pk_product");

                    b.HasIndex(new[] { "BrandId" }, "idx_product_brand_id");

                    b.HasIndex(new[] { "Name", "SuperMarketId", "BrandId" }, "idx_product_name_super_market_brand")
                        .IsUnique();

                    b.HasIndex(new[] { "SuperMarketId" }, "idx_product_super_market_id");

                    b.ToTable("products", "market", t =>
                        {
                            t.HasComment("Products available in the market");
                        });
                });

            modelBuilder.Entity("Metaspesa.Database.Entities.ProductsHistoryDbEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<float>("Price")
                        .HasColumnType("real")
                        .HasColumnName("price");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<string>("Quantity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("pk_product_history");

                    b.HasIndex(new[] { "CreatedAt" }, "idx_product_history_created_at");

                    b.HasIndex(new[] { "ProductId" }, "idx_product_history_product_id");

                    b.ToTable("products_history", "market", t =>
                        {
                            t.HasComment("Historical price and quantity data for products, tracking changes over time");

                            t.HasCheckConstraint("chk_positive_price", "price >= 0.00");
                        });
                });

            modelBuilder.Entity("Metaspesa.Database.Entities.PurchaseDbEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("PricePaid")
                        .HasColumnType("real")
                        .HasColumnName("price_paid");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<DateTime>("PurchasedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purchased_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Quantity")
                        .HasColumnType("text")
                        .HasColumnName("quantity");

                    b.Property<int>("RegisteredItemId")
                        .HasColumnType("integer")
                        .HasColumnName("registered_item_id");

                    b.Property<int?>("SuperMarketId")
                        .HasColumnType("integer")
                        .HasColumnName("super_market_id");

                    b.Property<Guid>("UserUid")
                        .HasColumnType("uuid")
                        .HasColumnName("user_uid");

                    b.HasKey("Id")
                        .HasName("pk_purchase");

                    b.HasIndex(new[] { "ProductId" }, "idx_purchase_product_id");

                    b.HasIndex(new[] { "PurchasedAt" }, "idx_purchase_purchased_at");

                    b.HasIndex(new[] { "RegisteredItemId" }, "idx_purchase_registered_item_id");

                    b.HasIndex(new[] { "SuperMarketId" }, "idx_purchase_super_market_id");

                    b.HasIndex(new[] { "UserUid" }, "idx_purchase_user_uid");

                    b.ToTable("purchases", "shopping", t =>
                        {
                            t.HasComment("Records the actual act of buying an item — links shopping, registered\r\nitems, and the market. Core of savings analytics.");

                            t.HasCheckConstraint("chk_positive_price_paid", "price_paid >= 0.00");
                        });
                });

            modelBuilder.Entity("Metaspesa.Database.Entities.RegisteredItemDbEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("LastKnownPrice")
                        .HasColumnType("real")
                        .HasColumnName("last_known_price");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Quantity")
                        .HasColumnType("text")
                        .HasColumnName("quantity");

                    b.Property<Guid>("UserUid")
                        .HasColumnType("uuid")
                        .HasColumnName("user_uid");

                    b.HasKey("Id")
                        .HasName("pk_registered_item");

                    b.HasIndex(new[] { "UserUid" }, "idx_registered_item_user_uid");

                    b.ToTable("registered_items", "shopping", t =>
                        {
                            t.HasComment("Items that users have registered as purchased or planned to purchase");

                            t.HasCheckConstraint("chk_positive_last_known_price", "last_known_price >= 0.00");
                        });
                });

            modelBuilder.Entity("Metaspesa.Database.Entities.ShoppingItemDbEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_checked");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<float>("Price")
                        .HasColumnType("real")
                        .HasColumnName("price");

                    b.Property<string>("Quantity")
                        .HasColumnType("text")
                        .HasColumnName("quantity");

                    b.Property<int>("ShoppingListId")
                        .HasColumnType("integer")
                        .HasColumnName("shopping_list_id");

                    b.HasKey("Id")
                        .HasName("pk_shopping_item");

                    b.HasIndex(new[] { "ShoppingListId" }, "idx_shopping_item_shopping_list_id");

                    b.ToTable("shopping_items", "shopping", t =>
                        {
                            t.HasComment("Items that belong to a shopping list, representing planned purchases");

                            t.HasCheckConstraint("chk_shopping_item_positive_price", "price >= 0.00");
                        });
                });

            modelBuilder.Entity("Metaspesa.Database.Entities.ShoppingListDbEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name")
                        .HasComment("Missing name indicates a temporary shopping list, not saved by the user");

                    b.HasKey("Id")
                        .HasName("pk_shopping_list");

                    b.ToTable("shopping_lists", "shopping", t =>
                        {
                            t.HasComment("Shopping lists created by users, can be shared among multiple users");

                            t.HasCheckConstraint("chk_shopping_list_temporary_cannot_be_soft_deleted", "name IS NOT NULL OR deleted_at IS NULL");
                        });
                });

            modelBuilder.Entity("Metaspesa.Database.Entities.ShoppingListOwnershipDbEntity", b =>
                {
                    b.Property<Guid>("UserUid")
                        .HasColumnType("uuid")
                        .HasColumnName("user_uid");

                    b.Property<int>("ShoppingListId")
                        .HasColumnType("integer")
                        .HasColumnName("shopping_list_id");

                    b.HasKey("UserUid", "ShoppingListId")
                        .HasName("pk_shopping_list_ownership");

                    b.HasIndex(new[] { "ShoppingListId" }, "idx_shopping_list_ownership_shopping_list_id");

                    b.HasIndex(new[] { "UserUid" }, "idx_shopping_list_ownership_user_uid");

                    b.ToTable("shopping_list_ownerships", "shopping", t =>
                        {
                            t.HasComment("Associates users with shopping lists, allowing for shared lists");
                        });
                });

            modelBuilder.Entity("Metaspesa.Database.Entities.SuperMarketDbEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_super_market");

                    b.HasIndex(new[] { "Name" }, "idx_super_market_name")
                        .IsUnique();

                    b.ToTable("super_markets", "market", t =>
                        {
                            t.HasComment("Supermarkets where products are available");
                        });
                });

            modelBuilder.Entity("Metaspesa.Database.Entities.UserDbEntity", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EncryptedPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("encrypted_password");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("username");

                    b.HasKey("Uid")
                        .HasName("pk_user");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Username" }, "idx_user_username")
                        .IsUnique();

                    b.ToTable("users", "shopping", t =>
                        {
                            t.HasComment("Registered users of the shopping application");
                        });
                });

            modelBuilder.Entity("Metaspesa.Database.Entities.UserRoleDbEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_role");

                    b.HasIndex(new[] { "Name" }, "idx_role_name")
                        .IsUnique();

                    b.ToTable("roles", "shopping", t =>
                        {
                            t.HasComment("User roles for access control");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Regular user who manages shopping lists",
                            Name = "Shopper"
                        },
                        new
                        {
                            Id = 2,
                            Description = "User who manages market products",
                            Name = "ProductManager"
                        });
                });

            modelBuilder.Entity("Metaspesa.Database.Entities.ProductDbEntity", b =>
                {
                    b.HasOne("Metaspesa.Database.Entities.ProductBrandDbEntity", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Metaspesa.Database.Entities.SuperMarketDbEntity", "SuperMarket")
                        .WithMany("Products")
                        .HasForeignKey("SuperMarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("SuperMarket");
                });

            modelBuilder.Entity("Metaspesa.Database.Entities.ProductsHistoryDbEntity", b =>
                {
                    b.HasOne("Metaspesa.Database.Entities.ProductDbEntity", "Product")
                        .WithMany("History")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Metaspesa.Database.Entities.PurchaseDbEntity", b =>
                {
                    b.HasOne("Metaspesa.Database.Entities.ProductDbEntity", "Product")
                        .WithMany("Purchases")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Metaspesa.Database.Entities.RegisteredItemDbEntity", "RegisteredItem")
                        .WithMany("Purchases")
                        .HasForeignKey("RegisteredItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Metaspesa.Database.Entities.SuperMarketDbEntity", "SuperMarket")
                        .WithMany("Purchases")
                        .HasForeignKey("SuperMarketId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Metaspesa.Database.Entities.UserDbEntity", "User")
                        .WithMany("Purchases")
                        .HasForeignKey("UserUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("RegisteredItem");

                    b.Navigation("SuperMarket");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Metaspesa.Database.Entities.RegisteredItemDbEntity", b =>
                {
                    b.HasOne("Metaspesa.Database.Entities.UserDbEntity", "User")
                        .WithMany("RegisteredItems")
                        .HasForeignKey("UserUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Metaspesa.Database.Entities.ShoppingItemDbEntity", b =>
                {
                    b.HasOne("Metaspesa.Database.Entities.ShoppingListDbEntity", "ShoppingList")
                        .WithMany("Items")
                        .HasForeignKey("ShoppingListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShoppingList");
                });

            modelBuilder.Entity("Metaspesa.Database.Entities.ShoppingListOwnershipDbEntity", b =>
                {
                    b.HasOne("Metaspesa.Database.Entities.ShoppingListDbEntity", "ShoppingList")
                        .WithMany("Ownerships")
                        .HasForeignKey("ShoppingListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Metaspesa.Database.Entities.UserDbEntity", "Owner")
                        .WithMany("Ownerships")
                        .HasForeignKey("UserUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("ShoppingList");
                });

            modelBuilder.Entity("Metaspesa.Database.Entities.UserDbEntity", b =>
                {
                    b.HasOne("Metaspesa.Database.Entities.UserRoleDbEntity", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Metaspesa.Database.Entities.ProductBrandDbEntity", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Metaspesa.Database.Entities.ProductDbEntity", b =>
                {
                    b.Navigation("History");

                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("Metaspesa.Database.Entities.RegisteredItemDbEntity", b =>
                {
                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("Metaspesa.Database.Entities.ShoppingListDbEntity", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Ownerships");
                });

            modelBuilder.Entity("Metaspesa.Database.Entities.SuperMarketDbEntity", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("Metaspesa.Database.Entities.UserDbEntity", b =>
                {
                    b.Navigation("Ownerships");

                    b.Navigation("Purchases");

                    b.Navigation("RegisteredItems");
                });

            modelBuilder.Entity("Metaspesa.Database.Entities.UserRoleDbEntity", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
