// <auto-generated />
using System;
using Metaspesa.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Metaspesa.Database.Migrations {
  [DbContext(typeof(MainContext))]
  [Migration("20260925211912_UseUuidV7Ids")]
  partial class UseUuidV7Ids {
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder) {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "10.0.12")
          .HasAnnotation("Relational:MaxIdentifierLength", 63);

      NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

      modelBuilder.Entity("Metaspesa.Database.Entities.PriceSnapshotDbEntity", b => {
        b.Property<Guid>("Id")
            .HasColumnType("uuid")
            .HasColumnName("id");

        b.Property<string>("CurrencyCode")
            .IsRequired()
            .ValueGeneratedOnAdd()
            .HasColumnType("char(3)")
            .HasDefaultValue("EUR")
            .HasColumnName("currency_code");

        b.Property<DateTime>("ObservedAt")
            .ValueGeneratedOnAdd()
            .HasColumnType("timestamp with time zone")
            .HasColumnName("observed_at")
            .HasDefaultValueSql("now()");

        b.Property<decimal>("PriceAmount")
            .HasPrecision(10, 2)
            .HasColumnType("numeric(10,2)")
            .HasColumnName("price_amount");

        b.Property<Guid>("ProductFormatId")
            .HasColumnType("uuid")
            .HasColumnName("product_format_id");

        b.HasKey("Id")
            .HasName("pk_price_snapshot");

        b.HasIndex(new[] { "ProductFormatId", "ObservedAt" }, "idx_price_snapshot_format_observed_at");

        b.HasIndex(new[] { "ObservedAt" }, "idx_price_snapshot_observed_at");

        b.HasIndex(new[] { "ProductFormatId" }, "idx_price_snapshot_product_format_id");

        b.ToTable("price_snapshots", "market", t => {
          t.HasComment("Historical price observations for product formats.");

          t.HasCheckConstraint("chk_price_snapshot_currency_code", "currency_code ~ '^[A-Z]{3}$'");

          t.HasCheckConstraint("chk_price_snapshot_positive_price", "price_amount > 0.00");
        });
      });

      modelBuilder.Entity("Metaspesa.Database.Entities.ProductBrandDbEntity", b => {
        b.Property<Guid>("Id")
            .HasColumnType("uuid")
            .HasColumnName("id");

        b.Property<string>("Name")
            .IsRequired()
            .HasColumnType("text")
            .HasColumnName("name");

        b.HasKey("Id")
            .HasName("pk_product_brand");

        b.HasIndex(new[] { "Name" }, "idx_product_brand_name")
            .IsUnique();

        b.ToTable("product_brands", "market", t => {
          t.HasComment("Brands of products available in the market");
        });
      });

      modelBuilder.Entity("Metaspesa.Database.Entities.ProductDbEntity", b => {
        b.Property<Guid>("Id")
            .HasColumnType("uuid")
            .HasColumnName("id");

        b.Property<Guid>("BrandId")
            .HasColumnType("uuid")
            .HasColumnName("brand_id");

        b.Property<string>("Name")
            .IsRequired()
            .HasColumnType("text")
            .HasColumnName("name");

        b.Property<Guid>("SuperMarketId")
            .HasColumnType("uuid")
            .HasColumnName("super_market_id");

        b.HasKey("Id")
            .HasName("pk_product");

        b.HasIndex(new[] { "BrandId" }, "idx_product_brand_id");

        b.HasIndex(new[] { "Name", "SuperMarketId", "BrandId" }, "idx_product_name_super_market_brand")
            .IsUnique();

        b.HasIndex(new[] { "SuperMarketId" }, "idx_product_super_market_id");

        b.ToTable("products", "market", t => {
          t.HasComment("Products available in the market");
        });
      });

      modelBuilder.Entity("Metaspesa.Database.Entities.ProductFormatDbEntity", b => {
        b.Property<Guid>("Id")
            .HasColumnType("uuid")
            .HasColumnName("id");

        b.Property<string>("ImageUrl")
            .IsRequired()
            .HasColumnType("text")
            .HasColumnName("image_url");

        b.Property<Guid>("ProductId")
            .HasColumnType("uuid")
            .HasColumnName("product_id");

        b.Property<decimal>("Quantity")
            .HasPrecision(10, 3)
            .HasColumnType("numeric(10,3)")
            .HasColumnName("quantity");

        b.Property<Guid>("UnitOfMeasureId")
            .HasColumnType("uuid")
            .HasColumnName("unit_of_measure_id");

        b.HasKey("Id")
            .HasName("pk_product_format");

        b.HasAlternateKey("Id", "ProductId")
            .HasName("ak_product_format_id_product_id");

        b.HasIndex(new[] { "ProductId", "Quantity", "UnitOfMeasureId" }, "idx_product_format_identity")
            .IsUnique();

        b.HasIndex(new[] { "ProductId" }, "idx_product_format_product_id");

        b.HasIndex(new[] { "UnitOfMeasureId" }, "idx_product_format_unit_of_measure_id");

        b.ToTable("product_formats", "market", t => {
          t.HasComment("Different package formats for the same product. For example, a soda can be sold\nin 330 ml cans, 500 ml bottles, or 1 l bottles.");

          t.HasCheckConstraint("chk_product_format_positive_quantity", "quantity > 0.000");
        });
      });

      modelBuilder.Entity("Metaspesa.Database.Entities.PurchaseDbEntity", b => {
        b.Property<Guid>("Id")
            .HasColumnType("uuid")
            .HasColumnName("id");

        b.Property<DateTime>("PurchasedAt")
            .ValueGeneratedOnAdd()
            .HasColumnType("timestamp with time zone")
            .HasColumnName("purchased_at")
            .HasDefaultValueSql("now()");

        b.Property<Guid?>("ShoppingListId")
            .HasColumnType("uuid")
            .HasColumnName("shopping_list_id");

        b.Property<Guid?>("UserUid")
            .HasColumnType("uuid")
            .HasColumnName("user_uid");

        b.HasKey("Id")
            .HasName("pk_purchase");

        b.HasIndex(new[] { "PurchasedAt" }, "idx_purchases_purchased_at");

        b.HasIndex(new[] { "ShoppingListId" }, "idx_purchases_shopping_list_id");

        b.HasIndex(new[] { "UserUid" }, "idx_purchases_user_uid");

        b.ToTable("purchases", "purchasing", t => {
          t.HasComment("Purchase receipt header. It records who bought, when, and optionally which\nshopping list was checked out. Product lines live in purchase_items.");
        });
      });

      modelBuilder.Entity("Metaspesa.Database.Entities.PurchaseItemDbEntity", b => {
        b.Property<Guid>("Id")
            .HasColumnType("uuid")
            .HasColumnName("id");

        b.Property<int>("Amount")
            .ValueGeneratedOnAdd()
            .HasColumnType("integer")
            .HasDefaultValue(1)
            .HasColumnName("amount")
            .HasComment("How many units/packages were bought");

        b.Property<Guid>("PriceSnapshotId")
            .HasColumnType("uuid")
            .HasColumnName("price_snapshot_id");

        b.Property<Guid>("PurchaseId")
            .HasColumnType("uuid")
            .HasColumnName("purchase_id");

        b.HasKey("Id")
            .HasName("pk_purchase_item");

        b.HasIndex(new[] { "PriceSnapshotId" }, "idx_purchase_item_price_snapshot_id");

        b.HasIndex(new[] { "PurchaseId" }, "idx_purchase_item_purchase_id");

        b.ToTable("purchase_items", "purchasing", t => {
          t.HasComment("Immutable purchase receipt lines. Each line references the exact market\nprice snapshot used at purchase time.");

          t.HasCheckConstraint("chk_purchase_item_positive_amount", "amount > 0");
        });
      });

      modelBuilder.Entity("Metaspesa.Database.Entities.ShoppingItemDbEntity", b => {
        b.Property<Guid>("Id")
            .HasColumnType("uuid")
            .HasColumnName("id");

        b.Property<int>("Amount")
            .ValueGeneratedOnAdd()
            .HasColumnType("integer")
            .HasDefaultValue(1)
            .HasColumnName("amount")
            .HasComment("How many units/packages of the product are planned");

        b.Property<DateTime?>("DeletedAt")
            .HasColumnType("timestamp with time zone")
            .HasColumnName("deleted_at");

        b.Property<bool>("IsChecked")
            .ValueGeneratedOnAdd()
            .HasColumnType("boolean")
            .HasDefaultValue(false)
            .HasColumnName("is_checked");

        b.Property<Guid>("ProductFormatId")
            .HasColumnType("uuid")
            .HasColumnName("product_format_id");

        b.Property<Guid>("ShoppingListId")
            .HasColumnType("uuid")
            .HasColumnName("shopping_list_id");

        b.HasKey("Id")
            .HasName("pk_shopping_item");

        b.HasIndex(new[] { "ShoppingListId", "ProductFormatId" }, "idx_shopping_item_list_product_format");

        b.HasIndex(new[] { "ShoppingListId", "ProductFormatId" }, "idx_shopping_item_list_product_format_active")
            .IsUnique()
            .HasFilter("deleted_at IS NULL");

        b.HasIndex(new[] { "ProductFormatId" }, "idx_shopping_item_product_format_id");

        b.HasIndex(new[] { "ShoppingListId" }, "idx_shopping_item_shopping_list_id");

        b.ToTable("shopping_items", "shopping", t => {
          t.HasComment("Items that belong to a shopping list, representing planned purchases.\nEach line points to an existing product format.");

          t.HasCheckConstraint("chk_shopping_item_positive_amount", "amount > 0");
        });
      });

      modelBuilder.Entity("Metaspesa.Database.Entities.ShoppingListDbEntity", b => {
        b.Property<Guid>("Id")
            .HasColumnType("uuid")
            .HasColumnName("id");

        b.Property<DateTime?>("DeletedAt")
            .HasColumnType("timestamp with time zone")
            .HasColumnName("deleted_at");

        b.Property<bool>("IsTemporary")
            .ValueGeneratedOnAdd()
            .HasColumnType("boolean")
            .HasDefaultValue(false)
            .HasColumnName("is_temporary");

        b.Property<string>("Name")
            .HasColumnType("text")
            .HasColumnName("name");

        b.HasKey("Id")
            .HasName("pk_shopping_list");

        b.ToTable("shopping_lists", "shopping", t => {
          t.HasComment("Shopping lists created by users, can be shared among multiple users");

          t.HasCheckConstraint("chk_saved_shopping_list_requires_name", "is_temporary = true OR name IS NOT NULL");

          t.HasCheckConstraint("chk_shopping_list_temporary_cannot_be_soft_deleted", "is_temporary = false OR deleted_at IS NULL");
        });
      });

      modelBuilder.Entity("Metaspesa.Database.Entities.ShoppingListOwnershipDbEntity", b => {
        b.Property<Guid>("UserUid")
            .HasColumnType("uuid")
            .HasColumnName("user_uid");

        b.Property<Guid>("ShoppingListId")
            .HasColumnType("uuid")
            .HasColumnName("shopping_list_id");

        b.HasKey("UserUid", "ShoppingListId")
            .HasName("pk_shopping_list_ownership");

        b.HasIndex(new[] { "ShoppingListId" }, "idx_shopping_list_ownership_shopping_list_id");

        b.HasIndex(new[] { "UserUid" }, "idx_shopping_list_ownership_user_uid");

        b.ToTable("shopping_list_ownerships", "shopping", t => {
          t.HasComment("Associates users with shopping lists, allowing for shared lists");
        });
      });

      modelBuilder.Entity("Metaspesa.Database.Entities.SuperMarketDbEntity", b => {
        b.Property<Guid>("Id")
            .HasColumnType("uuid")
            .HasColumnName("id");

        b.Property<string>("LogoUrl")
            .HasColumnType("text")
            .HasColumnName("logo_url");

        b.Property<string>("Name")
            .IsRequired()
            .HasColumnType("text")
            .HasColumnName("name");

        b.HasKey("Id")
            .HasName("pk_super_market");

        b.HasIndex(new[] { "Name" }, "idx_super_market_name")
            .IsUnique();

        b.ToTable("super_markets", "market", t => {
          t.HasComment("Supermarkets where products are available");
        });
      });

      modelBuilder.Entity("Metaspesa.Database.Entities.UnitOfMeasureDbEntity", b => {
        b.Property<Guid>("Id")
            .HasColumnType("uuid")
            .HasColumnName("id");

        b.Property<string>("Code")
            .IsRequired()
            .HasMaxLength(16)
            .HasColumnType("character varying(16)")
            .HasColumnName("code")
            .HasComment("Stable unit code, e.g. ml, kg, piece");

        b.Property<string>("Name")
            .IsRequired()
            .HasMaxLength(64)
            .HasColumnType("character varying(64)")
            .HasColumnName("name");

        b.HasKey("Id")
            .HasName("pk_unit_of_measure");

        b.HasIndex(new[] { "Code" }, "idx_unit_of_measure_code")
            .IsUnique();

        b.ToTable("units_of_measure", "market", t => {
          t.HasComment("Units used to describe product package format, not shopping count.\nExamples: ml, l, g, kg, piece.");
        });
      });

      modelBuilder.Entity("Metaspesa.Database.Entities.UserDbEntity", b => {
        b.Property<Guid>("Uid")
            .HasColumnType("uuid")
            .HasColumnName("uid");

        b.Property<string>("EncryptedPassword")
            .IsRequired()
            .HasMaxLength(255)
            .HasColumnType("character varying(255)")
            .HasColumnName("encrypted_password");

        b.Property<int>("RoleId")
            .HasColumnType("integer")
            .HasColumnName("role_id");

        b.Property<string>("Username")
            .IsRequired()
            .HasMaxLength(255)
            .HasColumnType("character varying(255)")
            .HasColumnName("username");

        b.HasKey("Uid")
            .HasName("pk_user");

        b.HasIndex(new[] { "RoleId" }, "idx_user_role_id");

        b.HasIndex(new[] { "Username" }, "idx_user_username")
            .IsUnique();

        b.ToTable("users", "identity", t => {
          t.HasComment("Registered users of the shopping application");
        });
      });

      modelBuilder.Entity("Metaspesa.Database.Entities.UserRoleDbEntity", b => {
        b.Property<int>("Id")
            .HasColumnType("integer")
            .HasColumnName("id");

        b.Property<string>("Description")
            .IsRequired()
            .HasMaxLength(255)
            .HasColumnType("character varying(255)")
            .HasColumnName("description");

        b.Property<string>("Name")
            .IsRequired()
            .HasMaxLength(100)
            .HasColumnType("character varying(100)")
            .HasColumnName("name");

        b.HasKey("Id")
            .HasName("pk_role");

        b.HasIndex(new[] { "Name" }, "idx_role_name")
            .IsUnique();

        b.ToTable("roles", "identity", t => {
          t.HasComment("User roles for access control");
        });

        b.HasData(
            new {
              Id = 1,
              Description = "Regular user who manages shopping lists",
              Name = "Shopper"
            },
            new {
              Id = 2,
              Description = "User who manages market products",
              Name = "ProductManager"
            });
      });

      modelBuilder.Entity("Metaspesa.Database.Entities.PriceSnapshotDbEntity", b => {
        b.HasOne("Metaspesa.Database.Entities.ProductFormatDbEntity", "ProductFormat")
            .WithMany("PriceSnapshots")
            .HasForeignKey("ProductFormatId")
            .OnDelete(DeleteBehavior.Restrict)
            .IsRequired();

        b.Navigation("ProductFormat");
      });

      modelBuilder.Entity("Metaspesa.Database.Entities.ProductDbEntity", b => {
        b.HasOne("Metaspesa.Database.Entities.ProductBrandDbEntity", "Brand")
            .WithMany("Products")
            .HasForeignKey("BrandId")
            .OnDelete(DeleteBehavior.Restrict)
            .IsRequired();

        b.HasOne("Metaspesa.Database.Entities.SuperMarketDbEntity", "SuperMarket")
            .WithMany("Products")
            .HasForeignKey("SuperMarketId")
            .OnDelete(DeleteBehavior.Restrict)
            .IsRequired();

        b.Navigation("Brand");

        b.Navigation("SuperMarket");
      });

      modelBuilder.Entity("Metaspesa.Database.Entities.ProductFormatDbEntity", b => {
        b.HasOne("Metaspesa.Database.Entities.ProductDbEntity", "Product")
            .WithMany("Formats")
            .HasForeignKey("ProductId")
            .OnDelete(DeleteBehavior.Restrict)
            .IsRequired();

        b.HasOne("Metaspesa.Database.Entities.UnitOfMeasureDbEntity", "UnitOfMeasure")
            .WithMany("ProductFormats")
            .HasForeignKey("UnitOfMeasureId")
            .OnDelete(DeleteBehavior.Restrict)
            .IsRequired();

        b.Navigation("Product");

        b.Navigation("UnitOfMeasure");
      });

      modelBuilder.Entity("Metaspesa.Database.Entities.PurchaseDbEntity", b => {
        b.HasOne("Metaspesa.Database.Entities.ShoppingListDbEntity", "ShoppingList")
            .WithMany("Purchases")
            .HasForeignKey("ShoppingListId")
            .OnDelete(DeleteBehavior.SetNull);

        b.HasOne("Metaspesa.Database.Entities.UserDbEntity", "User")
            .WithMany("Purchases")
            .HasForeignKey("UserUid")
            .OnDelete(DeleteBehavior.SetNull);

        b.Navigation("ShoppingList");

        b.Navigation("User");
      });

      modelBuilder.Entity("Metaspesa.Database.Entities.PurchaseItemDbEntity", b => {
        b.HasOne("Metaspesa.Database.Entities.PriceSnapshotDbEntity", "PriceSnapshot")
            .WithMany("PurchaseItems")
            .HasForeignKey("PriceSnapshotId")
            .OnDelete(DeleteBehavior.Restrict)
            .IsRequired();

        b.HasOne("Metaspesa.Database.Entities.PurchaseDbEntity", "Purchase")
            .WithMany("Items")
            .HasForeignKey("PurchaseId")
            .OnDelete(DeleteBehavior.Cascade)
            .IsRequired();

        b.Navigation("PriceSnapshot");

        b.Navigation("Purchase");
      });

      modelBuilder.Entity("Metaspesa.Database.Entities.ShoppingItemDbEntity", b => {
        b.HasOne("Metaspesa.Database.Entities.ProductFormatDbEntity", "ProductFormat")
            .WithMany("ShoppingItems")
            .HasForeignKey("ProductFormatId")
            .OnDelete(DeleteBehavior.Restrict)
            .IsRequired();

        b.HasOne("Metaspesa.Database.Entities.ShoppingListDbEntity", "ShoppingList")
            .WithMany("Items")
            .HasForeignKey("ShoppingListId")
            .OnDelete(DeleteBehavior.Cascade)
            .IsRequired();

        b.Navigation("ProductFormat");

        b.Navigation("ShoppingList");
      });

      modelBuilder.Entity("Metaspesa.Database.Entities.ShoppingListOwnershipDbEntity", b => {
        b.HasOne("Metaspesa.Database.Entities.ShoppingListDbEntity", "ShoppingList")
            .WithMany("Ownerships")
            .HasForeignKey("ShoppingListId")
            .OnDelete(DeleteBehavior.Cascade)
            .IsRequired();

        b.HasOne("Metaspesa.Database.Entities.UserDbEntity", "Owner")
            .WithMany("Ownerships")
            .HasForeignKey("UserUid")
            .OnDelete(DeleteBehavior.Cascade)
            .IsRequired();

        b.Navigation("Owner");

        b.Navigation("ShoppingList");
      });

      modelBuilder.Entity("Metaspesa.Database.Entities.UserDbEntity", b => {
        b.HasOne("Metaspesa.Database.Entities.UserRoleDbEntity", "Role")
            .WithMany("Users")
            .HasForeignKey("RoleId")
            .OnDelete(DeleteBehavior.Restrict)
            .IsRequired();

        b.Navigation("Role");
      });

      modelBuilder.Entity("Metaspesa.Database.Entities.PriceSnapshotDbEntity", b => {
        b.Navigation("PurchaseItems");
      });

      modelBuilder.Entity("Metaspesa.Database.Entities.ProductBrandDbEntity", b => {
        b.Navigation("Products");
      });

      modelBuilder.Entity("Metaspesa.Database.Entities.ProductDbEntity", b => {
        b.Navigation("Formats");
      });

      modelBuilder.Entity("Metaspesa.Database.Entities.ProductFormatDbEntity", b => {
        b.Navigation("PriceSnapshots");

        b.Navigation("ShoppingItems");
      });

      modelBuilder.Entity("Metaspesa.Database.Entities.PurchaseDbEntity", b => {
        b.Navigation("Items");
      });

      modelBuilder.Entity("Metaspesa.Database.Entities.ShoppingListDbEntity", b => {
        b.Navigation("Items");

        b.Navigation("Ownerships");

        b.Navigation("Purchases");
      });

      modelBuilder.Entity("Metaspesa.Database.Entities.SuperMarketDbEntity", b => {
        b.Navigation("Products");
      });

      modelBuilder.Entity("Metaspesa.Database.Entities.UnitOfMeasureDbEntity", b => {
        b.Navigation("ProductFormats");
      });

      modelBuilder.Entity("Metaspesa.Database.Entities.UserDbEntity", b => {
        b.Navigation("Ownerships");

        b.Navigation("Purchases");
      });

      modelBuilder.Entity("Metaspesa.Database.Entities.UserRoleDbEntity", b => {
        b.Navigation("Users");
      });
#pragma warning restore 612, 618
    }
  }
}
