// <auto-generated />
using System;
using Metaspesa.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Metaspesa.Database.Migrations
{
    [DbContext(typeof(MainContext))]
    partial class MainContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Metaspesa.Database.Entities.RegisteredItemDbEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Quantity")
                        .HasColumnType("text")
                        .HasColumnName("quantity");

                    b.Property<Guid>("UserUid")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UserUid");

                    b.ToTable("registered_items", (string)null);
                });

            modelBuilder.Entity("Metaspesa.Database.Entities.RegisteredItemsHistoryDbEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<float?>("Price")
                        .HasColumnType("real")
                        .HasColumnName("price");

                    b.Property<int>("RegisteredItemId")
                        .HasColumnType("integer")
                        .HasColumnName("registered_item_id");

                    b.HasKey("Id");

                    b.HasIndex("RegisteredItemId");

                    b.ToTable("registered_items_history", (string)null);
                });

            modelBuilder.Entity("Metaspesa.Database.Entities.ShoppingItemDbEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsChecked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_checked");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<float?>("Price")
                        .HasColumnType("real")
                        .HasColumnName("price");

                    b.Property<string>("Quantity")
                        .HasColumnType("text")
                        .HasColumnName("quantity");

                    b.Property<int>("ShoppingListId")
                        .HasColumnType("integer")
                        .HasColumnName("shopping_list_id");

                    b.HasKey("Id");

                    b.HasIndex("ShoppingListId");

                    b.ToTable("shopping_items", (string)null);
                });

            modelBuilder.Entity("Metaspesa.Database.Entities.ShoppingListDbEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("shopping_lists", (string)null);
                });

            modelBuilder.Entity("Metaspesa.Database.Entities.ShoppingListOwnershipDbEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastTimeUsed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_time_used");

                    b.Property<int>("ShoppingListId")
                        .HasColumnType("integer")
                        .HasColumnName("shopping_list_id");

                    b.Property<Guid>("UserUid")
                        .HasColumnType("uuid")
                        .HasColumnName("user_uid");

                    b.HasKey("Id");

                    b.HasIndex("ShoppingListId");

                    b.HasIndex("UserUid");

                    b.ToTable("shopping_list_ownerships", (string)null);
                });

            modelBuilder.Entity("Metaspesa.Database.Entities.UserDbEntity", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("uid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Uid");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Metaspesa.Database.Entities.RegisteredItemDbEntity", b =>
                {
                    b.HasOne("Metaspesa.Database.Entities.UserDbEntity", "User")
                        .WithMany("RegisteredItems")
                        .HasForeignKey("UserUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Metaspesa.Database.Entities.RegisteredItemsHistoryDbEntity", b =>
                {
                    b.HasOne("Metaspesa.Database.Entities.RegisteredItemDbEntity", "RegisteredItem")
                        .WithMany("History")
                        .HasForeignKey("RegisteredItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegisteredItem");
                });

            modelBuilder.Entity("Metaspesa.Database.Entities.ShoppingItemDbEntity", b =>
                {
                    b.HasOne("Metaspesa.Database.Entities.ShoppingListDbEntity", "ShoppingList")
                        .WithMany("Items")
                        .HasForeignKey("ShoppingListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShoppingList");
                });

            modelBuilder.Entity("Metaspesa.Database.Entities.ShoppingListOwnershipDbEntity", b =>
                {
                    b.HasOne("Metaspesa.Database.Entities.ShoppingListDbEntity", "ShoppingList")
                        .WithMany("Ownerships")
                        .HasForeignKey("ShoppingListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Metaspesa.Database.Entities.UserDbEntity", "User")
                        .WithMany("ShoppingListOwnerships")
                        .HasForeignKey("UserUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShoppingList");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Metaspesa.Database.Entities.RegisteredItemDbEntity", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("Metaspesa.Database.Entities.ShoppingListDbEntity", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Ownerships");
                });

            modelBuilder.Entity("Metaspesa.Database.Entities.UserDbEntity", b =>
                {
                    b.Navigation("RegisteredItems");

                    b.Navigation("ShoppingListOwnerships");
                });
#pragma warning restore 612, 618
        }
    }
}
