services:
  alloy:
    image: grafana/alloy:v1.16.1
    volumes:
      - ./observability/alloy/config.alloy:/etc/alloy/config.alloy
    command: run /etc/alloy/config.alloy
    networks:
      - metaspesa_telemetry_default

  loki:
    image: grafana/loki:3.7
    volumes:
      - ./observability/loki/loki.yaml:/etc/loki/loki.yaml
      - loki_data:/loki
    command: -config.file=/etc/loki/loki.yaml
    networks:
      - metaspesa_telemetry_default

  mimir:
    image: grafana/mimir:3.0.6
    volumes:
      - ./observability/mimir/mimir.yaml:/etc/mimir/mimir.yaml
      - mimir_data:/var/mimir
    command: -config.file=/etc/mimir/mimir.yaml
    networks:
      - metaspesa_telemetry_default

  tempo:
    image: grafana/tempo:2.10.5
    volumes:
      - ./observability/tempo/tempo.yaml:/etc/tempo/tempo.yaml
      - tempo_data:/var/tempo
    command: -config.file=/etc/tempo/tempo.yaml
    networks:
      - metaspesa_telemetry_default

  grafana:
    image: grafana/grafana:13.0.1
    ports:
      - 3001:3000
    env_file:
      - .env
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "false"
      GF_SECURITY_ADMIN_PASSWORD: "${GRAFANA_PASSWORD}"
    volumes:
      - ./observability/grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    networks:
      - metaspesa_telemetry_default

volumes:
  loki_data:
  mimir_data:
  tempo_data:
  grafana_data:

networks:
  metaspesa_telemetry_default:
    external: true
