services:
  server:
    image: gianluisdiana/metaspesa_server:latest
    build:
      context: ./server
      dockerfile: ./src/GrpcApi/Dockerfile
    ports:
      - 5000:8080
    environment:
      ASPNETCORE_URLS: http://+:8080
      POSTGRES_CONNECTION_STRING: Host=db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      OTEL_EXPORTER_OTLP_ENDPOINT: http://alloy:4317
    env_file:
      - .env
    secrets:
      - jwt_secret_key
    networks:
      - default
      - metaspesa_telemetry_default

  migrations:
    image: gianluisdiana/metaspesa_migrations:latest
    build:
      context: ./server
      dockerfile: ./src/MigrationService/Dockerfile
    profiles:
      - tools
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_CONNECTION_STRING: Host=db;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      OTEL_EXPORTER_OTLP_ENDPOINT: http://alloy:4317
    env_file:
      - .env
    networks:
      - default
      - metaspesa_telemetry_default

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: gianluisdiana/metaspesa_client:latest
    ports:
      - 3000:8080
    depends_on:
      - server
    environment:
      GRPC_SERVER_URL: server:8080
      PORT: 8080

  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    image: gianluisdiana/metaspesa_scraper:latest
    depends_on:
      - server
    environment:
      GRPC_SERVER_URL: server:8080
      OTEL_EXPORTER_OTLP_ENDPOINT: http://alloy:4317
    volumes:
      - scraper_data:/app/data
    secrets:
      - scraper_username
      - scraper_password
    networks:
      - default
      - metaspesa_telemetry_default

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - default
      - metaspesa_telemetry_default

volumes:
  db_data:
  scraper_data:

networks:
  metaspesa_telemetry_default:
    external: true

secrets:
  jwt_secret_key:
    file: ./secrets/jwt_secret_key
  scraper_username:
    file: ./secrets/scraper_username
  scraper_password:
    file: ./secrets/scraper_password
