services:
  alloy:
    image: grafana/alloy:latest
    volumes:
      - ./observability/alloy/config.alloy:/etc/alloy/config.alloy
    command: run /etc/alloy/config.alloy
    ports:
      - 4317:4317
    networks:
      - metaspesa_telemetry_default

  loki:
    image: grafana/loki:latest
    volumes:
      - ./observability/loki/loki.yaml:/etc/loki/loki.yaml
      - loki_data:/loki
    command: -config.file=/etc/loki/loki.yaml
    networks:
      - metaspesa_telemetry_default

  mimir:
    image: grafana/mimir:latest
    volumes:
      - ./observability/mimir/mimir.yaml:/etc/mimir/mimir.yaml
      - mimir_data:/var/mimir
    command: -config.file=/etc/mimir/mimir.yaml
    networks:
      - metaspesa_telemetry_default

  tempo:
    image: grafana/tempo:latest
    volumes:
      - ./observability/tempo/tempo.yaml:/etc/tempo/tempo.yaml
      - tempo_data:/var/tempo
    command: -config.file=/etc/tempo/tempo.yaml
    networks:
      - metaspesa_telemetry_default

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3001:3000
    env_file:
      - .env
    volumes:
      - ./observability/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - metaspesa_telemetry_default

volumes:
  loki_data:
  mimir_data:
  tempo_data:

networks:
  metaspesa_telemetry_default:
    external: true
