#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER grafana WITH PASSWORD '$GRAFANA_DB_PASSWORD';
  GRANT CONNECT ON DATABASE "$POSTGRES_DB" TO grafana;
  GRANT USAGE ON SCHEMA public TO grafana;
  GRANT SELECT ON ALL TABLES IN SCHEMA public TO grafana;
  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO grafana;
EOSQL
