apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: loki
    url: https://loki:3100
    isDefault: true
    jsonData:
      tlsAuth: true
      tlsAuthWithCACert: true
    secureJsonData:
      tlsCACert: ${TELEMETRY_CA_PEM}
      tlsClientCert: ${TELEMETRY_CLIENT_CERT_PEM}
      tlsClientKey: ${TELEMETRY_CLIENT_KEY_PEM}
