apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: loki
    url: https://loki:3100
    isDefault: true
    jsonData:
      tlsAuth: true
      tlsAuthWithCACert: true
    secureJsonData:
      tlsCACert: $__file{/run/secrets/telemetry_ca}
      tlsClientCert: $__file{/run/secrets/telemetry_client_cert}
      tlsClientKey: $__file{/run/secrets/telemetry_client_key}
