apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: db:5432
    user: grafana
    secureJsonData:
      password: ${GRAFANA_DB_PASSWORD}
    jsonData:
      database: ${POSTGRES_DB}
      sslmode: disable
      postgresVersion: 1500
      maxOpenConns: 10
      maxIdleConns: 10
      connMaxLifetime: 14400
