apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    uid: tempo
    url: https://tempo:3200
    jsonData:
      tlsAuth: true
      tlsAuthWithCACert: true
      tracesToLogsV2:
        datasourceUid: loki
        filterByTraceID: true
        filterBySpanID: true
        tags:
          - key: service.name
            value: service_name
    secureJsonData:
      tlsCACert: ${TELEMETRY_CA_PEM}
      tlsClientCert: ${TELEMETRY_CLIENT_CERT_PEM}
      tlsClientKey: ${TELEMETRY_CLIENT_KEY_PEM}
