apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    uid: tempo
    url: https://tempo:3200
    jsonData:
      tlsAuth: true
      tlsAuthWithCACert: true
      tracesToLogsV2:
        datasourceUid: loki
        filterByTraceID: true
        filterBySpanID: true
        tags:
          - key: service.name
            value: service_name
    secureJsonData:
      tlsCACert: $__file{/run/secrets/telemetry_ca}
      tlsClientCert: $__file{/run/secrets/telemetry_client_cert}
      tlsClientKey: $__file{/run/secrets/telemetry_client_key}
