#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER grafana WITH PASSWORD '$GRAFANA_DB_PASSWORD';
  GRANT CONNECT ON DATABASE "$POSTGRES_DB" TO grafana;
  ALTER DEFAULT PRIVILEGES GRANT USAGE ON SCHEMAS TO grafana;
  ALTER DEFAULT PRIVILEGES GRANT SELECT ON TABLES TO grafana;
EOSQL
