# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: infrastructure/grpc/protos/auth_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'infrastructure/grpc/protos/auth_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-infrastructure/grpc/protos/auth_service.proto\x12\x15Metaspesa.Protos.Auth\x1a\x1bgoogle/protobuf/empty.proto\"5\n\x0fRegisterRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"9\n\rLoginResponse\x12\r\n\x05token\x18\x01 \x01(\t\x12\x19\n\x11\x65xpiration_in_utc\x18\x02 \x01(\t2\xad\x01\n\x0b\x41uthService\x12J\n\x08Register\x12&.Metaspesa.Protos.Auth.RegisterRequest\x1a\x16.google.protobuf.Empty\x12R\n\x05Login\x12#.Metaspesa.Protos.Auth.LoginRequest\x1a$.Metaspesa.Protos.Auth.LoginResponseB \xaa\x02\x1dMetaspesa.GrpcApi.Protos.Authb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'infrastructure.grpc.protos.auth_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\035Metaspesa.GrpcApi.Protos.Auth'
  _globals['_REGISTERREQUEST']._serialized_start=101
  _globals['_REGISTERREQUEST']._serialized_end=154
  _globals['_LOGINREQUEST']._serialized_start=156
  _globals['_LOGINREQUEST']._serialized_end=206
  _globals['_LOGINRESPONSE']._serialized_start=208
  _globals['_LOGINRESPONSE']._serialized_end=265
  _globals['_AUTHSERVICE']._serialized_start=268
  _globals['_AUTHSERVICE']._serialized_end=441
# @@protoc_insertion_point(module_scope)
