# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from infrastructure.grpc.protos import auth_service_pb2 as infrastructure_dot_grpc_dot_protos_dot_auth__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in infrastructure/grpc/protos/auth_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthServiceStub(object):
    """Handles the authentication related operations.
    """

    def __init__(self, channel: grpc.aio.Channel):
        """Constructor.

        Args:
            channel: A grpc.aio.Channel.
        """
        self.Register = channel.unary_unary(
                '/Metaspesa.Protos.Auth.AuthService/Register',
                request_serializer=infrastructure_dot_grpc_dot_protos_dot_auth__service__pb2.RegisterRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/Metaspesa.Protos.Auth.AuthService/Login',
                request_serializer=infrastructure_dot_grpc_dot_protos_dot_auth__service__pb2.LoginRequest.SerializeToString,
                response_deserializer=infrastructure_dot_grpc_dot_protos_dot_auth__service__pb2.LoginResponse.FromString,
                _registered_method=True)


class AuthServiceServicer(object):
    """Handles the authentication related operations.
    """

    def Register(self, request, context):
        """Registers a new user with the provided credentials.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Logs in a user with the provided credentials.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=infrastructure_dot_grpc_dot_protos_dot_auth__service__pb2.RegisterRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=infrastructure_dot_grpc_dot_protos_dot_auth__service__pb2.LoginRequest.FromString,
                    response_serializer=infrastructure_dot_grpc_dot_protos_dot_auth__service__pb2.LoginResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Metaspesa.Protos.Auth.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Metaspesa.Protos.Auth.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """Handles the authentication related operations.
    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Metaspesa.Protos.Auth.AuthService/Register',
            infrastructure_dot_grpc_dot_protos_dot_auth__service__pb2.RegisterRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Metaspesa.Protos.Auth.AuthService/Login',
            infrastructure_dot_grpc_dot_protos_dot_auth__service__pb2.LoginRequest.SerializeToString,
            infrastructure_dot_grpc_dot_protos_dot_auth__service__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
