// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Items to add to a shopping list.
 */
export type AddShoppingItemsRequest = {
    /**
     * Non-empty array of items with distinct product format IDs.
     */
    items: null | Array<ShoppingItemRequest>;
};

/**
 * Details for a new named or temporary shopping list.
 */
export type CreateShoppingListRequest = {
    /**
     * List name, or null to create a temporary list.
     */
    name: null | string;
};

/**
 * Credentials supplied when registering or authenticating a shopper.
 */
export type CredentialsRequest = {
    /**
     * Shopper username used to identify the account.
     */
    username: string;
    /**
     * Plaintext password for this request; never returned in responses.
     */
    password: string;
};

/**
 * Purchasable product format with its latest price observation.
 */
export type FormatResponse = {
    /**
     * Stable format ID used as the shopping-list item reference.
     */
    id: number;
    /**
     * Amount and unit sold in this format.
     */
    quantity: QuantityResponse;
    /**
     * Latest observed price for this format.
     */
    currentPrice: MoneyResponse;
    /**
     * UTC instant of the latest price observation.
     */
    observedAt: string;
    /**
     * Absolute product image URL when available; otherwise omitted.
     */
    imageUrl?: null | string;
};

/**
 * Identifier of a newly created shopping list.
 */
export type IdResponse = {
    /**
     * Stable shopping list ID.
     */
    id: number;
};

/**
 * Markets available in the catalog.
 */
export type MarketListResponse = {
    /**
     * Market summaries; empty when no markets are registered.
     */
    items: Array<MarketResponse>;
};

/**
 * Market identity and display information.
 */
export type MarketResponse = {
    /**
     * Stable market ID used by the catalog marketId filter.
     */
    id: number;
    /**
     * Display name of the market.
     */
    name: string;
    /**
     * Absolute logo URL when available; otherwise omitted.
     */
    logoUrl?: null | string;
};

/**
 * Monetary amount and currency.
 */
export type MoneyResponse = {
    /**
     * Price in the stated currency.
     */
    amount: number;
    /**
     * Currency code of the price, such as EUR.
     */
    currency: string;
};

/**
 * Error response with a machine-readable code and request trace identifier.
 */
export type ProblemDetails = {
    /**
     * URI identifying the class of problem.
     */
    type?: null | string;
    /**
     * Short human-readable reason for the failure.
     */
    title?: null | string;
    /**
     * HTTP status code of this response.
     */
    status?: null | number;
    /**
     * Additional detail when available.
     */
    detail?: null | string;
    /**
     * Request URI when available.
     */
    instance?: null | string;
    /**
     * Stable machine-readable error code.
     */
    code: string;
    /**
     * Request trace identifier for support and logs.
     */
    traceId: string;
};

/**
 * One page of matching products.
 */
export type ProductPageResponse = {
    /**
     * Products in this page; empty when none match.
     */
    items: Array<ProductResponse>;
    /**
     * One-based page number requested.
     */
    page: number;
    /**
     * Maximum number of products requested for this page.
     */
    pageSize: number;
    /**
     * Number of matching products across all pages.
     */
    totalItems: number;
    /**
     * Number of pages at this page size; zero when none match.
     */
    totalPages: number;
};

/**
 * One market-owned product. IDs do not imply cross-market equivalence.
 */
export type ProductResponse = {
    /**
     * Stable ID of this product.
     */
    id: number;
    /**
     * Product display name.
     */
    name: string;
    /**
     * Product brand display name.
     */
    brand: string;
    /**
     * Market that owns this product.
     */
    market: MarketResponse;
    /**
     * Available quantities and their latest observed prices.
     */
    formats: Array<FormatResponse>;
};

/**
 * Identifier of a recorded purchase.
 */
export type PurchaseResponse = {
    /**
     * Stable purchase ID.
     */
    purchaseId: number;
};

/**
 * Quantity associated with one product format.
 */
export type QuantityResponse = {
    /**
     * Numeric quantity of the format.
     */
    amount: number;
    /**
     * Unit of measure, such as kg, g, or l.
     */
    unit: string;
};

/**
 * New name for a shopping list.
 */
export type RenameShoppingListRequest = {
    /**
     * Required nonblank name for the list.
     */
    name: null | string;
};

/**
 * One product format to add to a shopping list.
 */
export type ShoppingItemRequest = {
    /**
     * ID of an existing product format.
     */
    productFormatId: number;
    /**
     * Positive number of units to buy.
     */
    amount: number;
    /**
     * Whether the item is marked for checkout.
     */
    checked: boolean;
};

/**
 * Shopping item with current product and price information.
 */
export type ShoppingItemResponse = {
    /**
     * Stable format ID used to update or remove this item.
     */
    productFormatId: number;
    /**
     * Product display name.
     */
    productName: string;
    /**
     * Product brand display name.
     */
    brand: string;
    /**
     * Market that sells the product.
     */
    market: ShoppingMarketResponse;
    /**
     * Quantity sold in one product format.
     */
    quantity: ShoppingQuantityResponse;
    /**
     * Latest observed price for one product format.
     */
    unitPrice: ShoppingMoneyResponse;
    /**
     * Positive number of units on the list.
     */
    amount: number;
    /**
     * Whether this item is marked for checkout.
     */
    checked: boolean;
    /**
     * Absolute product image URL when available; otherwise omitted.
     */
    imageUrl: null | string;
};

/**
 * Shopping lists owned by the authenticated shopper.
 */
export type ShoppingListCollectionResponse = {
    /**
     * List summaries; empty when the shopper owns no lists.
     */
    items: Array<ShoppingListSummaryResponse>;
};

/**
 * Shopping list and its current items.
 */
export type ShoppingListResponse = {
    /**
     * Stable shopping list ID.
     */
    id: number;
    /**
     * List name, omitted for a temporary list.
     */
    name: null | string;
    /**
     * Whether this is an unnamed temporary list.
     */
    isTemporary: boolean;
    /**
     * Items in the list; empty when it has no items.
     */
    items: Array<ShoppingItemResponse>;
};

/**
 * Shopping list identity and display information.
 */
export type ShoppingListSummaryResponse = {
    /**
     * Stable shopping list ID.
     */
    id: number;
    /**
     * List name, omitted for a temporary list.
     */
    name: null | string;
    /**
     * Whether this is the shopper's unnamed temporary list.
     */
    isTemporary: boolean;
};

/**
 * Market that sells a shopping item.
 */
export type ShoppingMarketResponse = {
    /**
     * Stable market ID.
     */
    id: number;
    /**
     * Market display name.
     */
    name: string;
};

/**
 * Latest observed price for one product format.
 */
export type ShoppingMoneyResponse = {
    /**
     * Price in the stated currency.
     */
    amount: number;
    /**
     * Currency code of the price, such as EUR.
     */
    currency: string;
};

/**
 * Quantity sold in one product format.
 */
export type ShoppingQuantityResponse = {
    /**
     * Numeric quantity of the format.
     */
    amount: number;
    /**
     * Unit of measure, such as kg, g, or l.
     */
    unit: string;
};

/**
 * One observed product format in a market snapshot.
 */
export type SnapshotItem = {
    /**
     * Required nonblank product name.
     */
    name: null | string;
    /**
     * Observed non-negative price amount.
     */
    price: number;
    /**
     * Positive amount sold in this format.
     */
    quantity: number;
    /**
     * Unit of the quantity; must be supported.
     */
    unitOfMeasure: null | string;
    /**
     * Required nonblank brand name.
     */
    brandName: null | string;
    /**
     * Optional absolute product image URL.
     */
    imageUrl: null | string;
};

/**
 * Batch of market product observations.
 */
export type SnapshotRequest = {
    /**
     * Non-empty array of valid product observations.
     */
    items: null | Array<SnapshotItem>;
};

/**
 * Bearer token issued after successful machine authentication.
 */
export type TokenResponse = {
    /**
     * JWT sent in the Authorization Bearer header.
     */
    accessToken: string;
    /**
     * Authorization scheme; always Bearer.
     */
    tokenType: string;
    /**
     * UTC instant after which the token is invalid.
     */
    expiresAt: string;
};

/**
 * Changes to a shopping item; at least one field is required.
 */
export type UpdateShoppingItemRequest = {
    /**
     * New positive amount, or null to keep the current amount.
     */
    amount: null | number;
    /**
     * New checked state, or null to keep the current state.
     */
    checked: null | boolean;
};

export type RegisterShopperData = {
    /**
     * Credentials supplied when registering or authenticating a shopper.
     */
    body: CredentialsRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/registrations';
};

export type RegisterShopperErrors = {
    /**
     * Username or password violates registration rules, or the body is invalid.
     */
    400: ProblemDetails;
    /**
     * The browser Origin header is missing or not allowed.
     */
    403: ProblemDetails;
    /**
     * The username is already registered.
     */
    409: ProblemDetails;
    /**
     * An unexpected server or database failure occurred.
     */
    500: ProblemDetails;
};

export type RegisterShopperError = RegisterShopperErrors[keyof RegisterShopperErrors];

export type RegisterShopperResponses = {
    /**
     * Account created; no response body.
     */
    201: unknown;
};

export type CreateBrowserSessionData = {
    /**
     * Credentials supplied when registering or authenticating a shopper.
     */
    body: CredentialsRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/sessions';
};

export type CreateBrowserSessionErrors = {
    /**
     * The request body is invalid.
     */
    400: ProblemDetails;
    /**
     * The username or password is incorrect.
     */
    401: ProblemDetails;
    /**
     * The browser Origin header is missing or not allowed.
     */
    403: ProblemDetails;
    /**
     * An unexpected server or database failure occurred.
     */
    500: ProblemDetails;
};

export type CreateBrowserSessionError = CreateBrowserSessionErrors[keyof CreateBrowserSessionErrors];

export type CreateBrowserSessionResponses = {
    /**
     * Authenticated. A session cookie is set; no response body.
     */
    204: void;
};

export type CreateBrowserSessionResponse = CreateBrowserSessionResponses[keyof CreateBrowserSessionResponses];

export type CreateMachineTokenData = {
    /**
     * Credentials supplied when registering or authenticating a shopper.
     */
    body: CredentialsRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/tokens';
};

export type CreateMachineTokenErrors = {
    /**
     * The request body is invalid.
     */
    400: ProblemDetails;
    /**
     * The username or password is incorrect.
     */
    401: ProblemDetails;
    /**
     * An unexpected server or database failure occurred.
     */
    500: ProblemDetails;
};

export type CreateMachineTokenError = CreateMachineTokenErrors[keyof CreateMachineTokenErrors];

export type CreateMachineTokenResponses = {
    /**
     * Authenticated. Returns a bearer token and its expiry.
     */
    200: TokenResponse;
};

export type CreateMachineTokenResponse = CreateMachineTokenResponses[keyof CreateMachineTokenResponses];

export type GetMarketsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/markets';
};

export type GetMarketsErrors = {
    /**
     * An unexpected server or database failure occurred.
     */
    500: ProblemDetails;
};

export type GetMarketsError = GetMarketsErrors[keyof GetMarketsErrors];

export type GetMarketsResponses = {
    /**
     * Available markets and their stable IDs.
     */
    200: MarketListResponse;
};

export type GetMarketsResponse = GetMarketsResponses[keyof GetMarketsResponses];

export type GetProductsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Case-insensitive product-name fragment. Omit to include all names.
         */
        query?: string;
        /**
         * Repeat to include products from several markets. IDs must be positive.
         */
        marketId?: Array<number>;
        /**
         * Case-insensitive brand-name fragment. Omit to include all brands.
         */
        brand?: string;
        /**
         * One-based page number; defaults to 1.
         */
        page?: number;
        /**
         * Maximum products per page, from 1 to 100; defaults to 24.
         */
        pageSize?: number;
        /**
         * Sort by name or lowest latest format price. Defaults to name.
         */
        sort?: 'name' | 'priceAsc' | 'priceDesc';
    };
    url: '/api/v1/products';
};

export type GetProductsErrors = {
    /**
     * A filter, market ID, page value, or sort value is invalid.
     */
    400: ProblemDetails;
    /**
     * An unexpected server or database failure occurred.
     */
    500: ProblemDetails;
};

export type GetProductsError = GetProductsErrors[keyof GetProductsErrors];

export type GetProductsResponses = {
    /**
     * Matching products and pagination counts. An empty page has no items.
     */
    200: ProductPageResponse;
};

export type GetProductsResponse = GetProductsResponses[keyof GetProductsResponses];

export type AddMarketSnapshotData = {
    /**
     * Batch of market product observations.
     */
    body: SnapshotRequest;
    path: {
        /**
         * Name of the observed market.
         */
        marketName: string;
        /**
         * Observation date in YYYY-MM-DD format, on or after 2023-01-01.
         */
        date: string;
    };
    query?: never;
    url: '/api/v1/markets/{marketName}/snapshots/{date}';
};

export type AddMarketSnapshotErrors = {
    /**
     * The date or a product observation is invalid.
     */
    400: ProblemDetails;
    /**
     * No valid authentication token was provided.
     */
    401: unknown;
    /**
     * The authenticated user lacks the ProductManager role.
     */
    403: unknown;
    /**
     * An unexpected server or database failure occurred.
     */
    500: ProblemDetails;
};

export type AddMarketSnapshotError = AddMarketSnapshotErrors[keyof AddMarketSnapshotErrors];

export type AddMarketSnapshotResponses = {
    /**
     * Snapshot imported; no response body.
     */
    204: void;
};

export type AddMarketSnapshotResponse = AddMarketSnapshotResponses[keyof AddMarketSnapshotResponses];

export type GetShoppingListsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/shopping-lists';
};

export type GetShoppingListsErrors = {
    /**
     * No valid authentication token was provided.
     */
    401: unknown;
    /**
     * The authenticated user lacks the Shopper role.
     */
    403: unknown;
    /**
     * An unexpected server or database failure occurred.
     */
    500: ProblemDetails;
};

export type GetShoppingListsError = GetShoppingListsErrors[keyof GetShoppingListsErrors];

export type GetShoppingListsResponses = {
    /**
     * Shopping list summaries; the collection can be empty.
     */
    200: ShoppingListCollectionResponse;
};

export type GetShoppingListsResponse = GetShoppingListsResponses[keyof GetShoppingListsResponses];

export type CreateShoppingListData = {
    /**
     * Details for a new named or temporary shopping list.
     */
    body: CreateShoppingListRequest;
    path?: never;
    query?: never;
    url: '/api/v1/shopping-lists';
};

export type CreateShoppingListErrors = {
    /**
     * The list name is invalid.
     */
    400: ProblemDetails;
    /**
     * No valid authentication token was provided.
     */
    401: unknown;
    /**
     * The authenticated user lacks the Shopper role.
     */
    403: unknown;
    /**
     * A list with this name or a temporary list already exists.
     */
    409: ProblemDetails;
    /**
     * An unexpected server or database failure occurred.
     */
    500: ProblemDetails;
};

export type CreateShoppingListError = CreateShoppingListErrors[keyof CreateShoppingListErrors];

export type CreateShoppingListResponses = {
    /**
     * List created; the response contains its ID and the Location header identifies it.
     */
    201: IdResponse;
};

export type CreateShoppingListResponse = CreateShoppingListResponses[keyof CreateShoppingListResponses];

export type GetShoppingListData = {
    body?: never;
    path: {
        /**
         * ID of the shopping list to retrieve.
         */
        listId: number;
    };
    query?: never;
    url: '/api/v1/shopping-lists/{listId}';
};

export type GetShoppingListErrors = {
    /**
     * The list ID is invalid.
     */
    400: ProblemDetails;
    /**
     * No valid authentication token was provided.
     */
    401: unknown;
    /**
     * The authenticated user lacks the Shopper role.
     */
    403: unknown;
    /**
     * The list or a referenced product format was not found.
     */
    404: ProblemDetails;
    /**
     * An unexpected server or database failure occurred.
     */
    500: ProblemDetails;
};

export type GetShoppingListError = GetShoppingListErrors[keyof GetShoppingListErrors];

export type GetShoppingListResponses = {
    /**
     * The shopping list and its items.
     */
    200: ShoppingListResponse;
};

export type GetShoppingListResponse = GetShoppingListResponses[keyof GetShoppingListResponses];

export type RenameShoppingListData = {
    /**
     * New name for a shopping list.
     */
    body: RenameShoppingListRequest;
    path: {
        /**
         * ID of the shopping list to rename.
         */
        listId: number;
    };
    query?: never;
    url: '/api/v1/shopping-lists/{listId}';
};

export type RenameShoppingListErrors = {
    /**
     * The list ID or new name is invalid.
     */
    400: ProblemDetails;
    /**
     * No valid authentication token was provided.
     */
    401: unknown;
    /**
     * The authenticated user lacks the Shopper role.
     */
    403: unknown;
    /**
     * The list was not found.
     */
    404: ProblemDetails;
    /**
     * Another list already has this name.
     */
    409: ProblemDetails;
    /**
     * An unexpected server or database failure occurred.
     */
    500: ProblemDetails;
};

export type RenameShoppingListError = RenameShoppingListErrors[keyof RenameShoppingListErrors];

export type RenameShoppingListResponses = {
    /**
     * List renamed; no response body.
     */
    204: void;
};

export type RenameShoppingListResponse = RenameShoppingListResponses[keyof RenameShoppingListResponses];

export type AddShoppingItemsData = {
    /**
     * Items to add to a shopping list.
     */
    body: AddShoppingItemsRequest;
    path: {
        /**
         * ID of the shopping list to update.
         */
        listId: number;
    };
    query?: never;
    url: '/api/v1/shopping-lists/{listId}/items';
};

export type AddShoppingItemsErrors = {
    /**
     * The list ID or items are invalid, or the collection is empty.
     */
    400: ProblemDetails;
    /**
     * No valid authentication token was provided.
     */
    401: unknown;
    /**
     * The authenticated user lacks the Shopper role.
     */
    403: unknown;
    /**
     * The list or a product format was not found.
     */
    404: ProblemDetails;
    /**
     * A product format is already in the list or repeated in the request.
     */
    409: ProblemDetails;
    /**
     * An unexpected server or database failure occurred.
     */
    500: ProblemDetails;
};

export type AddShoppingItemsError = AddShoppingItemsErrors[keyof AddShoppingItemsErrors];

export type AddShoppingItemsResponses = {
    /**
     * Items added; no response body.
     */
    204: void;
};

export type AddShoppingItemsResponse = AddShoppingItemsResponses[keyof AddShoppingItemsResponses];

export type RemoveShoppingItemData = {
    body?: never;
    path: {
        /**
         * ID of the shopping list containing the item.
         */
        listId: number;
        /**
         * ID of the item's product format.
         */
        productFormatId: number;
    };
    query?: never;
    url: '/api/v1/shopping-lists/{listId}/items/{productFormatId}';
};

export type RemoveShoppingItemErrors = {
    /**
     * The list or product format ID is invalid.
     */
    400: ProblemDetails;
    /**
     * No valid authentication token was provided.
     */
    401: unknown;
    /**
     * The authenticated user lacks the Shopper role.
     */
    403: unknown;
    /**
     * The list or item was not found.
     */
    404: ProblemDetails;
    /**
     * An unexpected server or database failure occurred.
     */
    500: ProblemDetails;
};

export type RemoveShoppingItemError = RemoveShoppingItemErrors[keyof RemoveShoppingItemErrors];

export type RemoveShoppingItemResponses = {
    /**
     * Item removed; no response body.
     */
    204: void;
};

export type RemoveShoppingItemResponse = RemoveShoppingItemResponses[keyof RemoveShoppingItemResponses];

export type UpdateShoppingItemData = {
    /**
     * Changes to a shopping item; at least one field is required.
     */
    body: UpdateShoppingItemRequest;
    path: {
        /**
         * ID of the shopping list containing the item.
         */
        listId: number;
        /**
         * ID of the item's product format.
         */
        productFormatId: number;
    };
    query?: never;
    url: '/api/v1/shopping-lists/{listId}/items/{productFormatId}';
};

export type UpdateShoppingItemErrors = {
    /**
     * An ID or amount is invalid, or neither field was supplied.
     */
    400: ProblemDetails;
    /**
     * No valid authentication token was provided.
     */
    401: unknown;
    /**
     * The authenticated user lacks the Shopper role.
     */
    403: unknown;
    /**
     * The list or item was not found.
     */
    404: ProblemDetails;
    /**
     * An unexpected server or database failure occurred.
     */
    500: ProblemDetails;
};

export type UpdateShoppingItemError = UpdateShoppingItemErrors[keyof UpdateShoppingItemErrors];

export type UpdateShoppingItemResponses = {
    /**
     * Item updated; no response body.
     */
    204: void;
};

export type UpdateShoppingItemResponse = UpdateShoppingItemResponses[keyof UpdateShoppingItemResponses];

export type CheckoutShoppingListData = {
    body?: never;
    path: {
        /**
         * ID of the shopping list to check out.
         */
        listId: number;
    };
    query?: never;
    url: '/api/v1/shopping-lists/{listId}/checkouts';
};

export type CheckoutShoppingListErrors = {
    /**
     * The list ID is invalid.
     */
    400: ProblemDetails;
    /**
     * No valid authentication token was provided.
     */
    401: unknown;
    /**
     * The authenticated user lacks the Shopper role.
     */
    403: unknown;
    /**
     * The list was not found.
     */
    404: ProblemDetails;
    /**
     * No items are checked or a checked item has no price snapshot.
     */
    409: ProblemDetails;
    /**
     * An unexpected server or database failure occurred.
     */
    500: ProblemDetails;
};

export type CheckoutShoppingListError = CheckoutShoppingListErrors[keyof CheckoutShoppingListErrors];

export type CheckoutShoppingListResponses = {
    /**
     * Purchase recorded; the response contains its ID.
     */
    201: PurchaseResponse;
};

export type CheckoutShoppingListResponse = CheckoutShoppingListResponses[keyof CheckoutShoppingListResponses];
