// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Credentials supplied when registering or authenticating a shopper.
 */
export type CredentialsRequest = {
    /**
     * Shopper username used to identify the account.
     */
    username: string;
    /**
     * Plaintext password supplied for this request; never returned in responses.
     */
    password: string;
};

/**
 * Purchasable product format with its latest price observation.
 */
export type FormatResponse = {
    /**
     * Stable format ID used as the shopping-list item reference.
     */
    id: number;
    /**
     * Amount and unit sold in this format.
     */
    quantity: QuantityResponse;
    /**
     * Latest observed price for this format.
     */
    currentPrice: MoneyResponse;
    /**
     * UTC instant of the latest price observation.
     */
    observedAt: string;
    /**
     * Absolute product image URL when available; otherwise omitted.
     */
    imageUrl?: null | string;
};

/**
 * Markets available in the catalog.
 */
export type MarketListResponse = {
    /**
     * Market summaries; empty when no markets are registered.
     */
    items: Array<MarketResponse>;
};

/**
 * Market identity and display information.
 */
export type MarketResponse = {
    /**
     * Stable market ID used by the catalog marketId filter.
     */
    id: number;
    /**
     * Display name of the market.
     */
    name: string;
    /**
     * Absolute logo URL when one is available; otherwise omitted.
     */
    logoUrl?: null | string;
};

/**
 * Monetary amount and currency.
 */
export type MoneyResponse = {
    /**
     * Price in the stated currency.
     */
    amount: number;
    /**
     * Currency code of the price, such as EUR.
     */
    currency: string;
};

/**
 * Error response. The code identifies the failure and traceId helps correlate logs.
 */
export type ProblemDetails = {
    /**
     * URI identifying the class of problem.
     */
    type?: null | string;
    /**
     * Short human-readable reason for the failure.
     */
    title?: null | string;
    /**
     * HTTP status code of this response.
     */
    status?: null | number;
    /**
     * Additional detail when available.
     */
    detail?: null | string;
    /**
     * Request URI when available.
     */
    instance?: null | string;
    /**
     * Stable machine-readable error code.
     */
    code: string;
    /**
     * Request trace identifier for support and logs.
     */
    traceId: string;
};

/**
 * One page of matching products.
 */
export type ProductPageResponse = {
    /**
     * Products in this page; never includes formats without observed prices.
     */
    items: Array<ProductResponse>;
    /**
     * One-based page number requested.
     */
    page: number;
    /**
     * Maximum number of products requested for this page.
     */
    pageSize: number;
    /**
     * Number of matching products across all pages.
     */
    totalItems: number;
    /**
     * Number of pages at this pageSize; zero when no products match.
     */
    totalPages: number;
};

/**
 * One product owned by one market. Product IDs do not imply cross-market equivalence.
 */
export type ProductResponse = {
    /**
     * Stable ID of this market-owned product.
     */
    id: number;
    /**
     * Product display name.
     */
    name: string;
    /**
     * Product brand display name.
     */
    brand: string;
    /**
     * Market that owns this product.
     */
    market: MarketResponse;
    /**
     * Available quantities and their latest observed prices.
     */
    formats: Array<FormatResponse>;
};

/**
 * Quantity associated with one product format.
 */
export type QuantityResponse = {
    /**
     * Numeric quantity of the format.
     */
    amount: number;
    /**
     * Unit of measure, such as kg, g, l, or unit.
     */
    unit: string;
};

/**
 * One observed product format in a market snapshot.
 */
export type SnapshotItem = {
    /**
     * Product name. Required by product validation.
     */
    name: null | string;
    /**
     * Observed non-negative price amount.
     */
    price: number;
    /**
     * Positive amount sold in this format.
     */
    quantity: number;
    /**
     * Unit of the quantity; must be supported by the catalog.
     */
    unitOfMeasure: null | string;
    /**
     * Required nonblank brand name.
     */
    brandName: null | string;
    /**
     * Optional absolute product image URL.
     */
    imageUrl: null | string;
};

/**
 * Batch of market product observations.
 */
export type SnapshotRequest = {
    /**
     * Observations to import. Must be a non-empty array of valid products.
     */
    items: null | Array<SnapshotItem>;
};

/**
 * Bearer token issued after successful machine authentication.
 */
export type TokenResponse = {
    /**
     * JWT to send in the Authorization: Bearer header.
     */
    accessToken: string;
    /**
     * Authorization scheme; always Bearer.
     */
    tokenType: string;
    /**
     * UTC instant after which the token is no longer valid.
     */
    expiresAt: string;
};

export type RegisterShopperData = {
    /**
     * Credentials for the new shopper account.
     */
    body: CredentialsRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/registrations';
};

export type RegisterShopperErrors = {
    /**
     * Username or password violates registration rules, or the request body is invalid.
     */
    400: ProblemDetails;
    /**
     * The browser Origin header is missing or not allowed.
     */
    403: ProblemDetails;
    /**
     * The username is already registered.
     */
    409: ProblemDetails;
    /**
     * An unexpected server or database failure occurred. Use traceId when reporting it.
     */
    500: ProblemDetails;
};

export type RegisterShopperError = RegisterShopperErrors[keyof RegisterShopperErrors];

export type RegisterShopperResponses = {
    /**
     * Account created. The response has no body.
     */
    201: unknown;
};

export type CreateBrowserSessionData = {
    /**
     * Credentials used to create the browser session.
     */
    body: CredentialsRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/sessions';
};

export type CreateBrowserSessionErrors = {
    /**
     * The request body is invalid.
     */
    400: ProblemDetails;
    /**
     * The username or password is incorrect.
     */
    401: ProblemDetails;
    /**
     * The browser Origin header is missing or not allowed.
     */
    403: ProblemDetails;
    /**
     * An unexpected server or database failure occurred. Use traceId when reporting it.
     */
    500: ProblemDetails;
};

export type CreateBrowserSessionError = CreateBrowserSessionErrors[keyof CreateBrowserSessionErrors];

export type CreateBrowserSessionResponses = {
    /**
     * Authenticated. A session cookie is set; the response has no body.
     */
    204: void;
};

export type CreateBrowserSessionResponse = CreateBrowserSessionResponses[keyof CreateBrowserSessionResponses];

export type CreateMachineTokenData = {
    /**
     * Credentials used to obtain a bearer token.
     */
    body: CredentialsRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/tokens';
};

export type CreateMachineTokenErrors = {
    /**
     * The request body is invalid.
     */
    400: ProblemDetails;
    /**
     * The username or password is incorrect.
     */
    401: ProblemDetails;
    /**
     * An unexpected server or database failure occurred. Use traceId when reporting it.
     */
    500: ProblemDetails;
};

export type CreateMachineTokenError = CreateMachineTokenErrors[keyof CreateMachineTokenErrors];

export type CreateMachineTokenResponses = {
    /**
     * Authenticated. Returns a bearer token and its expiry.
     */
    200: TokenResponse;
};

export type CreateMachineTokenResponse = CreateMachineTokenResponses[keyof CreateMachineTokenResponses];

export type GetMarketsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/markets';
};

export type GetMarketsErrors = {
    /**
     * An unexpected server or database failure occurred. Use traceId when reporting it.
     */
    500: ProblemDetails;
};

export type GetMarketsError = GetMarketsErrors[keyof GetMarketsErrors];

export type GetMarketsResponses = {
    /**
     * Available markets, including identifiers for the marketId filter.
     */
    200: MarketListResponse;
};

export type GetMarketsResponse = GetMarketsResponses[keyof GetMarketsResponses];

export type GetProductsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Case-insensitive product-name fragment. Omit to include all names.
         */
        query?: string;
        /**
         * Repeat this parameter to include products from several markets. Each ID must be positive.
         */
        marketId?: Array<number>;
        /**
         * Case-insensitive brand-name fragment. Omit to include all brands.
         */
        brand?: string;
        /**
         * One-based page number; defaults to 1.
         */
        page?: number;
        /**
         * Maximum products per page, from 1 to 100; defaults to 24.
         */
        pageSize?: number;
        /**
         * Sort by name, or by the lowest latest format price in ascending or descending order. Defaults to name.
         */
        sort?: 'name' | 'priceAsc' | 'priceDesc';
    };
    url: '/api/v1/products';
};

export type GetProductsErrors = {
    /**
     * A filter, page value, market ID, or sort value is invalid.
     */
    400: ProblemDetails;
    /**
     * An unexpected server or database failure occurred. Use traceId when reporting it.
     */
    500: ProblemDetails;
};

export type GetProductsError = GetProductsErrors[keyof GetProductsErrors];

export type GetProductsResponses = {
    /**
     * Matching products and pagination counts. An empty page has an empty items array.
     */
    200: ProductPageResponse;
};

export type GetProductsResponse = GetProductsResponses[keyof GetProductsResponses];

export type AddMarketSnapshotData = {
    /**
     * Product observations to import for the specified market and date.
     */
    body: SnapshotRequest;
    path: {
        /**
         * Name of the market whose products are being observed.
         */
        marketName: string;
        /**
         * Observation date in YYYY-MM-DD format, on or after 2023-01-01.
         */
        date: string;
    };
    query?: never;
    url: '/api/v1/markets/{marketName}/snapshots/{date}';
};

export type AddMarketSnapshotErrors = {
    /**
     * The date or a product observation is invalid.
     */
    400: ProblemDetails;
    /**
     * No valid authentication token was provided.
     */
    401: unknown;
    /**
     * The authenticated user lacks the ProductManager role.
     */
    403: unknown;
    /**
     * An unexpected server or database failure occurred. Use traceId when reporting it.
     */
    500: ProblemDetails;
};

export type AddMarketSnapshotError = AddMarketSnapshotErrors[keyof AddMarketSnapshotErrors];

export type AddMarketSnapshotResponses = {
    /**
     * Snapshot imported. The response has no body.
     */
    204: void;
};

export type AddMarketSnapshotResponse = AddMarketSnapshotResponses[keyof AddMarketSnapshotResponses];
