// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * Credentials supplied when registering or authenticating a shopper.
 */
export const zCredentialsRequest = z.object({
    username: z.string(),
    password: z.string()
});

/**
 * Market identity and display information.
 */
export const zMarketResponse = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    name: z.string(),
    logoUrl: z.string().nullish()
});

/**
 * Markets available in the catalog.
 */
export const zMarketListResponse = z.object({
    items: z.array(zMarketResponse)
});

/**
 * Monetary amount and currency.
 */
export const zMoneyResponse = z.object({
    amount: z.number(),
    currency: z.string()
});

/**
 * Error response. The code identifies the failure and traceId helps correlate logs.
 */
export const zProblemDetails = z.object({
    type: z.string().nullish(),
    title: z.string().nullish(),
    status: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }).nullish(),
    detail: z.string().nullish(),
    instance: z.string().nullish(),
    code: z.string(),
    traceId: z.string()
});

/**
 * Quantity associated with one product format.
 */
export const zQuantityResponse = z.object({
    amount: z.number(),
    unit: z.string()
});

/**
 * Purchasable product format with its latest price observation.
 */
export const zFormatResponse = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    quantity: zQuantityResponse,
    currentPrice: zMoneyResponse,
    observedAt: z.iso.datetime(),
    imageUrl: z.string().nullish()
});

/**
 * One product owned by one market. Product IDs do not imply cross-market equivalence.
 */
export const zProductResponse = z.object({
    id: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    name: z.string(),
    brand: z.string(),
    market: zMarketResponse,
    formats: z.array(zFormatResponse)
});

/**
 * One page of matching products.
 */
export const zProductPageResponse = z.object({
    items: z.array(zProductResponse),
    page: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    pageSize: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    totalItems: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    totalPages: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
});

/**
 * One observed product format in a market snapshot.
 */
export const zSnapshotItem = z.object({
    name: z.string().nullable(),
    price: z.number(),
    quantity: z.number(),
    unitOfMeasure: z.string().nullable(),
    brandName: z.string().nullable(),
    imageUrl: z.string().nullable()
});

/**
 * Batch of market product observations.
 */
export const zSnapshotRequest = z.object({
    items: z.array(zSnapshotItem).nullable()
});

/**
 * Bearer token issued after successful machine authentication.
 */
export const zTokenResponse = z.object({
    accessToken: z.string(),
    tokenType: z.string(),
    expiresAt: z.iso.datetime()
});

/**
 * Credentials for the new shopper account.
 */
export const zRegisterShopperBody = zCredentialsRequest;

/**
 * Credentials used to create the browser session.
 */
export const zCreateBrowserSessionBody = zCredentialsRequest;

/**
 * Authenticated. A session cookie is set; the response has no body.
 */
export const zCreateBrowserSessionResponse = z.void();

/**
 * Credentials used to obtain a bearer token.
 */
export const zCreateMachineTokenBody = zCredentialsRequest;

/**
 * Authenticated. Returns a bearer token and its expiry.
 */
export const zCreateMachineTokenResponse = zTokenResponse;

/**
 * Available markets, including identifiers for the marketId filter.
 */
export const zGetMarketsResponse = zMarketListResponse;

export const zGetProductsQuery = z.object({
    query: z.string().optional(),
    marketId: z.array(z.int().gte(1)).optional(),
    brand: z.string().optional(),
    page: z.int().gte(1).optional().default(1),
    pageSize: z.int().gte(1).lte(100).optional().default(24),
    sort: z.enum([
        'name',
        'priceAsc',
        'priceDesc'
    ]).optional()
});

/**
 * Matching products and pagination counts. An empty page has an empty items array.
 */
export const zGetProductsResponse = zProductPageResponse;

/**
 * Product observations to import for the specified market and date.
 */
export const zAddMarketSnapshotBody = zSnapshotRequest;

export const zAddMarketSnapshotPath = z.object({
    marketName: z.string(),
    date: z.string()
});

/**
 * Snapshot imported. The response has no body.
 */
export const zAddMarketSnapshotResponse = z.void();
