parsing:
  known_brands:
    - "Hacendado"
    - "Hellmann's"
    - "Ybarra"
    - "Libby's"
    - "J-Lek"
    - "Fuente Selecta"
    - "Solán de Cabras"
    - "Fonteide"
    - "Aquavia"
    - "Fontébil"
    - "Firgas"
    - "Aquarius"
    - "Iso drink"
    - "Monster"
    - "Red Bull"
    - "Enervit Sport"
    - "Zero"
    - "Coca-Cola"
    - "Pepsi"
    - "Fanta"

scrapers:
  alcampo:
    skipped_categories:
        - "Folletos y Promociones"
        - "Electrodomésticos"
        - "Tecnología"
        - "Hogar y Decoración"
        - "JARDÍN y TERRAZA"
        - "Mascotas"
        - "Juguetes"
        - "Papelería"
        - "Bricolaje"
        - "Automóvil"
        - "Libros"
        - "Deportes y Maletas"
        - "Textil"
        - "Campañas"