processor:
  known_brands:
    - "Adrian Gutierrez e Hijas"
    - "Alcampo"
    - "Alpro"
    - "Anitin"
    - "Aquarius"
    - "Aquavia"
    - "Bachman"
    - "Buitoni"
    - "Burgo de Arias"
    - "Campofrío"
    - "Candelarita"
    - "Casa Tarradellas"
    - "Casa Westfalia"
    - "Castillo de Holanda"
    - "Coca-Cola"
    - "Comeztier"
    - "Conde Duque"
    - "Danone"
    - "Dr. Oetker"
    - "Dulces La Plata"
    - "Durex"
    - "El Chef"
    - "El Palmar"
    - "El Tofio"
    - "Enervit Sport"
    - "Fanta"
    - "Firgas"
    - "Flor de Esgueva"
    - "Fonteide"
    - "Fontébil"
    - "Foodsy"
    - "Fuente Selecta"
    - "Galbani"
    - "Galbusera"
    - "Gallina Blanca"
    - "García Baquero"
    - "Giovanni Ferrari"
    - "Goodfella's"
    - "Gran Capitán"
    - "Hacendado"
    - "Hellmann's"
    - "Huercasa"
    - "Intimy"
    - "Inés Rosales"
    - "Iso drink"
    - "J-Lek"
    - "Juver"
    - "Kéfir"
    - "La Celestina"
    - "La Granja"
    - "La Tradicional Canaria"
    - "La niña del sur"
    - "Lazur"
    - "Levital"
    - "Libby's"
    - "Maxorata"
    - "Miree"
    - "Monster"
    - "Monte Duque"
    - "OH MY CHEESE!"
    - "Old Amsterdam"
    - "Oro de Holanda"
    - "POK"
    - "Patros"
    - "Pepsi"
    - "Picual Casa Juncal"
    - "Polasal"
    - "Red Bull"
    - "Ribeto"
    - "Rèvèrend"
    - "Sabroz"
    - "San Isidro"
    - "San Roque"
    - "Santa Teresa"
    - "Satisfier"
    - "Senza Peccato"
    - "Société"
    - "Solán de Cabras"
    - "TGT"
    - "Torremilano"
    - "Trevijano"
    - "Unusual foods"
    - "Vega Sotuelamos"
    - "Wasa"
    - "Ybarra"
    - "Zero"

  replacements:
    "Alcampo":
      - "Alcampo Cultivamos lo Bueno"
      - "Alcampo Ecológico"
      - "Alcampo Gourmet"
      - "Producto Alcampo"
      - "Auchan"
      - "Auchan Collection"
      - "IGP Alcampo producción controlada"
    "Hacendado":
      - "Deliplus"

scrapers:
  alcampo:
    skipped_categories:
      - "Folletos y Promociones"
      - "Electrodomésticos"
      - "Tecnología"
      - "Hogar y Decoración"
      - "JARDÍN y TERRAZA"
      - "Mascotas"
      - "Juguetes"
      - "Papelería"
      - "Bricolaje"
      - "Automóvil"
      - "Libros"
      - "Deportes y Maletas"
      - "Textil"
      - "Campañas"