name: Lint code

on: [push, pull_request]

jobs:
  lint_scraper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Ruff Linter
        uses: astral-sh/ruff-action@v3
        with:
          src: "scraper/src"

      - name: Run Ruff Formatter
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --check"
          src: "scraper/src"
